---
- name: sample book
  hosts: ansible_client
  remote_user: zeeshan
  become: true
  tasks:
    - name: copying file to destination
      become: true
      copy:
        src: ~/Documents/nginx.tar
        dest: /home/ubuntu/
        mode: 0777
    - name: loading docker image
      become: true
      command: docker load -i /home/ubuntu/nginx.tar 
    - name: running docker image
      become: true
      command: docker run -d nginx

